# Generated by Django 4.2.3 on 2024-10-05 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_comentario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'permissions': [('can_delete_any_comentario', 'Can delete any comentario')]},
        ),
    ]
