# Generated by Django 4.2.3 on 2024-10-06 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_alter_comentario_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'permissions': [('can_delete_any_comentario', 'Puede eliminar cualquier comentario')]},
        ),
    ]
