# Generated by Django 4.2.3 on 2024-10-12 00:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0006_denuncia_motivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='noticia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='noticias.noticia'),
            preserve_default=False,
        ),
    ]
