# Generated by Django 4.2.3 on 2024-10-15 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0007_denuncia_noticia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='motivo',
            field=models.TextField(max_length=1500),
        ),
    ]
