# Generated by Django 4.2.3 on 2024-10-09 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(default='fotos_perfil/predeterminado.jpg', upload_to='fotos_perfil/'),
        ),
    ]
