# Generated by Django 4.2.3 on 2024-10-15 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuario_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
