# Generated by Django 4.2.3 on 2024-10-16 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_usuario_is_blocked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='is_blocked',
        ),
        migrations.AddField(
            model_name='usuario',
            name='advertencia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='bloqueado',
            field=models.BooleanField(default=False),
        ),
    ]
