# Generated by Django 4.2.3 on 2024-10-16 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_remove_usuario_is_blocked_usuario_advertencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='advertencia',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
